In [1]:
import tensorflow as tf
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


True

In [2]:
import pandas as pd
import os
from skimage.transform import resize
from skimage.io import imread
import numpy as np
import matplotlib.pyplot as plt

In [3]:
#input
Categories=['with_mask','without_mask']
flat_data_arr=[] #input array
target_arr=[] #output array
datadir='C:/Users/Sanje/Documents/GitHub/PRS-PM-2021-09-15-GRP-3Musketeers-DetectiveMask/data' 
#C:\Users\Sanje\Documents\GitHub\PRS-PM-2021-09-15-GRP-3Musketeers-DetectiveMask\data
#/content/drive/MyDrive/ML
#path which contains all the categories of images
for i in Categories:
    
    print(f'loading... category : {i}')
    path=os.path.join(datadir,i)
    for img in os.listdir(path):
        img_array=imread(os.path.join(path,img))
        img_resized=resize(img_array,(150,150,3))
        flat_data_arr.append(img_resized.flatten())
        target_arr.append(Categories.index(i))
    print(f'loaded category:{i} successfully')
flat_data=np.array(flat_data_arr)
target=np.array(target_arr)
df=pd.DataFrame(flat_data) #dataframe
df['Target']=target
x=df.iloc[:,:-1] #input data 
y=df.iloc[:,-1] #output data

loading... category : with_mask
loaded category:with_mask successfully
loading... category : without_mask
loaded category:without_mask successfully


In [4]:
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=77,stratify=y)

gamma1, gamma2 = 0.1, 1
C1, C2 = 1, 10
hyperparams = (gamma1, C1), (gamma1, C2), (gamma2, C1), (gamma2, C2)

scaler = StandardScaler()  
scaler.fit(x_train)
x_train = scaler.transform(x_train)  
x_test = scaler.transform(x_test) 

svm_clfs = []
for gamma, C in hyperparams:
    svm_clf=SVC(kernel="poly",gamma=gamma, C=C) 
    svm_clf.fit(x_train,y_train)
    svm_clfs.append(svm_clf)




In [5]:
print (svm_clfs)

[SVC(C=1, gamma=0.1, kernel='poly'), SVC(C=10, gamma=0.1, kernel='poly'), SVC(C=1, gamma=1, kernel='poly'), SVC(C=10, gamma=1, kernel='poly')]


In [6]:
from sklearn.metrics import classification_report, confusion_matrix  
import sklearn.metrics as metrics
for i, svm_clf in enumerate(svm_clfs):
    predictions = svm_clf.predict(x_test)  
    gamma, C = hyperparams[i]
    print("r=", gamma, "C=", C)
    print("Accuracy=", metrics.accuracy_score(y_test, predictions))
    print(confusion_matrix(y_test,predictions))  
    print(classification_report(y_test,predictions))  

r= 0.1 C= 1
Accuracy= 0.885506287227002
[[631 114]
 [ 59 707]]
              precision    recall  f1-score   support

           0       0.91      0.85      0.88       745
           1       0.86      0.92      0.89       766

    accuracy                           0.89      1511
   macro avg       0.89      0.88      0.89      1511
weighted avg       0.89      0.89      0.89      1511

r= 0.1 C= 10
Accuracy= 0.885506287227002
[[631 114]
 [ 59 707]]
              precision    recall  f1-score   support

           0       0.91      0.85      0.88       745
           1       0.86      0.92      0.89       766

    accuracy                           0.89      1511
   macro avg       0.89      0.88      0.89      1511
weighted avg       0.89      0.89      0.89      1511

r= 1 C= 1
Accuracy= 0.885506287227002
[[631 114]
 [ 59 707]]
              precision    recall  f1-score   support

           0       0.91      0.85      0.88       745
           1       0.86      0.92      0.89      